services:
  crm-postgres:
    image: postgres:alpine3.23
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ${PROJECT_ROOT}/out:/var/lib/postgresql

  crm-redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  crm-minio:
    image: quay.io/minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data

  crm-keycloak:
    image: quay.io/keycloak/keycloak:26.3
    restart: unless-stopped
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # Настройки подключения к PostgreSQL
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://crm-postgres:5432/${DB_NAME}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_DB_SCHEMA: keycloak  # Рекомендуется выделить отдельную схему, чтобы не перемешивать таблицы
    ports:
      - '8080:8080'
    depends_on:
      - crm-postgres  # Keycloak не запустится, пока не поднимется Postgres


  crm-backend:
    build:
      context: ./backend    # Папка, где лежит код и package.json бэкенда
      dockerfile: Dockerfile # Имя файла внутри этой папки
    restart: unless-stopped
    environment:
      - DB_HOST=crm-postgres # Указываем имя докер-сервиса базы данных
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=crm-redis # Указываем имя докер-сервиса редиса
      - REDIS_PORT=${REDIS_PORT}
      - PORT=${APP_PORT:-3000}
      - HOST=${APP_DOMAIN:-localhost}
      # Переменные для работы Keycloak внутри Docker
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
    ports:
      - "${HOST_PORT:-3000}:${APP_PORT:-3000}"
    depends_on:
      - crm-postgres
      - crm-redis
      - crm-keycloak # Добавляем зависимость от Keycloak
      - crm-minio 

volumes:
  redis_data:
  minio_data: